language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
  - ruby-head
  - jruby-19mode
gemfile:
  - Gemfile.rails-3.2.x
  - Gemfile.rails-4.0.x
  - Gemfile.rails-4.1.x
  - Gemfile.rails-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: Gemfile.rails-head
