language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head
  - jruby-19mode
env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
